// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Bruger")]
public partial class Bruger
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(45)]
    public string Navn { get; set; }

    [Required]
    [StringLength(45)]
    public string Adgangskode { get; set; }

    [Required]
    [StringLength(45)]
    public string Email { get; set; }

    public int? CampusId { get; set; }

    public int? RolleId { get; set; }

    [ForeignKey("CampusId")]
    [InverseProperty("Brugers")]
    public virtual Campus Campus { get; set; }

    [ForeignKey("RolleId")]
    [InverseProperty("Brugers")]
    public virtual Rolle Rolle { get; set; }

    [InverseProperty("Bruger")]
    public virtual ICollection<Tilmelding> Tilmeldings { get; set; } = new List<Tilmelding>();

    [ForeignKey("BrugerId")]
    [InverseProperty("Brugers")]
    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}