// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Bruger")]
public partial class Bruger
{
    [Key]
    public int BrugerId { get; set; }

    [Required]
    [StringLength(45)]
    public string Navn { get; set; }

    [Required]
    [StringLength(45)]
    public string Brugernavn { get; set; }

    [Required]
    [StringLength(45)]
    public string Adgangskode { get; set; }

    [Required]
    [StringLength(45)]
    public string Email { get; set; }

    [Column("Campus_CampusId")]
    public int CampusCampusId { get; set; }

    [Column("Rolle_RolleId")]
    public int RolleRolleId { get; set; }

    [ForeignKey("CampusCampusId")]
    [InverseProperty("Brugers")]
    public virtual Campus CampusCampus { get; set; }

    [ForeignKey("RolleRolleId")]
    [InverseProperty("Brugers")]
    public virtual Rolle RolleRolle { get; set; }

    [InverseProperty("BrugerBruger")]
    public virtual ICollection<Tilmelding> Tilmeldings { get; set; } = new List<Tilmelding>();

    [ForeignKey("BrugerBrugerId")]
    [InverseProperty("BrugerBrugers")]
    public virtual ICollection<Event> EventEvents { get; set; } = new List<Event>();
}