// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[PrimaryKey("VareVareId", "CampusCampusId")]
[Table("CampusHarLagerbeholdning")]
public partial class CampusHarLagerbeholdning
{
    [Key]
    [Column("Vare_VareId")]
    public int VareVareId { get; set; }

    [Key]
    [Column("Campus_CampusId")]
    public int CampusCampusId { get; set; }

    public int AntalPåLager { get; set; }

    [ForeignKey("CampusCampusId")]
    [InverseProperty("CampusHarLagerbeholdnings")]
    public virtual Campus CampusCampus { get; set; }

    [ForeignKey("VareVareId")]
    [InverseProperty("CampusHarLagerbeholdnings")]
    public virtual Vare VareVare { get; set; }
}