// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Campus")]
public partial class Campus
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(45)]
    public string By { get; set; }

    [InverseProperty("Campus")]
    public virtual ICollection<Bruger> Brugers { get; set; } = new List<Bruger>();

    [InverseProperty("Campus")]
    public virtual ICollection<CampusHarLagerbeholdning> CampusHarLagerbeholdnings { get; set; } = new List<CampusHarLagerbeholdning>();
}