// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[PrimaryKey("VareId", "CampusId")]
[Table("CampusHarLagerbeholdning")]
public partial class CampusHarLagerbeholdning
{
    [Key]
    [Column("Vare_Id")]
    public int VareId { get; set; }

    [Key]
    [Column("Campus_Id")]
    public int CampusId { get; set; }

    public int AntalPåLager { get; set; }

    [ForeignKey("CampusId")]
    [InverseProperty("CampusHarLagerbeholdnings")]
    public virtual Campus Campus { get; set; }

    [ForeignKey("VareId")]
    [InverseProperty("CampusHarLagerbeholdnings")]
    public virtual Vare Vare { get; set; }
}