// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Event")]
public partial class Event
{
    [Key]
    public int EventId { get; set; }

    [Required]
    [StringLength(45)]
    public string Titel { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Starttid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Sluttid { get; set; }

    [Required]
    [StringLength(45)]
    public string Beskrivelse { get; set; }

    public bool Antalsbegrænsning { get; set; }

    [Required]
    [StringLength(45)]
    public string Lokation { get; set; }

    [Column("Kategori_KategoriId")]
    public int KategoriKategoriId { get; set; }

    [Column("Nyheder_NyhedId")]
    public int NyhederNyhedId { get; set; }

    [ForeignKey("KategoriKategoriId")]
    [InverseProperty("Events")]
    public virtual Kategori KategoriKategori { get; set; }

    [ForeignKey("NyhederNyhedId")]
    [InverseProperty("Events")]
    public virtual Nyheder NyhederNyhed { get; set; }

    [InverseProperty("EventEvent")]
    public virtual ICollection<Tilmelding> Tilmeldings { get; set; } = new List<Tilmelding>();

    [ForeignKey("EventEventId")]
    [InverseProperty("EventEvents")]
    public virtual ICollection<Bruger> BrugerBrugers { get; set; } = new List<Bruger>();
}