// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Event")]
public partial class Event
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(45)]
    public string Titel { get; set; }

    public DateOnly Dato { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Starttid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Sluttid { get; set; }

    [Required]
    [StringLength(45)]
    public string Beskrivelse { get; set; }

    public bool Antalsbegrænsning { get; set; }

    [Required]
    [StringLength(45)]
    public string Lokation { get; set; }

    [Column("Kategori_Id")]
    public int KategoriId { get; set; }

    [Column("Nyheder_Id")]
    public int NyhederId { get; set; }

    [ForeignKey("KategoriId")]
    [InverseProperty("Events")]
    public virtual Kategori Kategori { get; set; }

    [ForeignKey("NyhederId")]
    [InverseProperty("Events")]
    public virtual Nyheder Nyheder { get; set; }

    [InverseProperty("Event")]
    public virtual ICollection<Tilmelding> Tilmeldings { get; set; } = new List<Tilmelding>();

    [ForeignKey("EventId")]
    [InverseProperty("Events")]
    public virtual ICollection<Bruger> Brugers { get; set; } = new List<Bruger>();
}