// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Kategori")]
public partial class Kategori
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(45)]
    public string Type { get; set; }

    [InverseProperty("Kategori")]
    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}