// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

public partial class mvp2_dk_db_eventapplikationContext : DbContext
{
    public mvp2_dk_db_eventapplikationContext()
    {
    }

    public mvp2_dk_db_eventapplikationContext(DbContextOptions<mvp2_dk_db_eventapplikationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bruger> Brugers { get; set; }

    public virtual DbSet<Campus> Campuses { get; set; }

    public virtual DbSet<CampusHarLagerbeholdning> CampusHarLagerbeholdnings { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<Kategori> Kategoris { get; set; }

    public virtual DbSet<Nyheder> Nyheders { get; set; }

    public virtual DbSet<Rolle> Rolles { get; set; }

    public virtual DbSet<Tilmelding> Tilmeldings { get; set; }

    public virtual DbSet<Vare> Vares { get; set; }

    public virtual DbSet<VareType> VareTypes { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=mssql15.unoeuro.com;Initial Catalog=mvp2_dk_db_eventapplikation;Persist Security Info=True;User ID=mvp2_dk;Password=tkxf4wy25DdgFz6aRHbe");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bruger>(entity =>
        {
            entity.HasKey(e => e.BrugerId).HasName("PK__Bruger__6FA2FB100D40047E");

            entity.Property(e => e.BrugerId).ValueGeneratedNever();

            entity.HasOne(d => d.CampusCampus).WithMany(p => p.Brugers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bruger__Campus_C__5629CD9C");

            entity.HasOne(d => d.RolleRolle).WithMany(p => p.Brugers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bruger__Rolle_Ro__571DF1D5");

            entity.HasMany(d => d.EventEvents).WithMany(p => p.BrugerBrugers)
                .UsingEntity<Dictionary<string, object>>(
                    "BrugerAdministrererEvent",
                    r => r.HasOne<Event>().WithMany()
                        .HasForeignKey("EventEventId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__BrugerAdm__Event__60A75C0F"),
                    l => l.HasOne<Bruger>().WithMany()
                        .HasForeignKey("BrugerBrugerId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__BrugerAdm__Bruge__5FB337D6"),
                    j =>
                    {
                        j.HasKey("BrugerBrugerId", "EventEventId").HasName("PK__BrugerAd__C9066C6DA3B35E24");
                        j.ToTable("BrugerAdministrererEvent");
                        j.IndexerProperty<int>("BrugerBrugerId").HasColumnName("Bruger_BrugerId");
                        j.IndexerProperty<int>("EventEventId").HasColumnName("Event_EventId");
                    });
        });

        modelBuilder.Entity<Campus>(entity =>
        {
            entity.HasKey(e => e.CampusId).HasName("PK__Campus__FD598DD60C5815F3");

            entity.Property(e => e.CampusId).ValueGeneratedNever();
        });

        modelBuilder.Entity<CampusHarLagerbeholdning>(entity =>
        {
            entity.HasKey(e => new { e.VareVareId, e.CampusCampusId }).HasName("PK__CampusHa__091F710E2C2C864C");

            entity.HasOne(d => d.CampusCampus).WithMany(p => p.CampusHarLagerbeholdnings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CampusHar__Campu__6754599E");

            entity.HasOne(d => d.VareVare).WithMany(p => p.CampusHarLagerbeholdnings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CampusHar__Vare___66603565");
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__Event__7944C8102E52CD6C");

            entity.Property(e => e.EventId).ValueGeneratedNever();

            entity.HasOne(d => d.KategoriKategori).WithMany(p => p.Events)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Event__Kategori___4E88ABD4");

            entity.HasOne(d => d.NyhederNyhed).WithMany(p => p.Events)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Event__Nyheder_N__4F7CD00D");
        });

        modelBuilder.Entity<Kategori>(entity =>
        {
            entity.HasKey(e => e.KategoriId).HasName("PK__Kategori__1782CC722E19CF04");

            entity.Property(e => e.KategoriId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Nyheder>(entity =>
        {
            entity.HasKey(e => e.NyhedId).HasName("PK__Nyheder__1506A37469274D57");

            entity.Property(e => e.NyhedId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Rolle>(entity =>
        {
            entity.HasKey(e => e.RolleId).HasName("PK__Rolle__36225527890427DC");

            entity.Property(e => e.RolleId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Tilmelding>(entity =>
        {
            entity.HasKey(e => e.TilmeldtId).HasName("PK__Tilmeldi__DD2B1B6BBDB33E89");

            entity.Property(e => e.TilmeldtId).ValueGeneratedNever();

            entity.HasOne(d => d.BrugerBruger).WithMany(p => p.Tilmeldings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Tilmeldin__Bruge__59FA5E80");

            entity.HasOne(d => d.EventEvent).WithMany(p => p.Tilmeldings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Tilmeldin__Event__5AEE82B9");
        });

        modelBuilder.Entity<Vare>(entity =>
        {
            entity.HasKey(e => e.VareId).HasName("PK__Vare__E1E51A012F187BC0");

            entity.Property(e => e.VareId).ValueGeneratedNever();

            entity.HasOne(d => d.VareTypeVareType).WithMany(p => p.Vares)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Vare__VareType_V__6383C8BA");
        });

        modelBuilder.Entity<VareType>(entity =>
        {
            entity.HasKey(e => e.VareTypeId).HasName("PK__VareType__9603CE253082E8AB");

            entity.Property(e => e.VareTypeId).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}