// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

public partial class mvp2_dk_db_eventapplikationContext : DbContext
{
    public mvp2_dk_db_eventapplikationContext()
    {
    }

    public mvp2_dk_db_eventapplikationContext(DbContextOptions<mvp2_dk_db_eventapplikationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bruger> Brugers { get; set; }

    public virtual DbSet<Campus> Campuses { get; set; }

    public virtual DbSet<CampusHarLagerbeholdning> CampusHarLagerbeholdnings { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<Kategori> Kategoris { get; set; }

    public virtual DbSet<Nyheder> Nyheders { get; set; }

    public virtual DbSet<Rolle> Rolles { get; set; }

    public virtual DbSet<Tilmelding> Tilmeldings { get; set; }

    public virtual DbSet<Vare> Vares { get; set; }

    public virtual DbSet<VareType> VareTypes { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)

        => optionsBuilder.UseSqlServer("Data Source=mssql15.unoeuro.com;Initial Catalog=mvp2_dk_db_eventapplikation;Persist Security Info=True;User ID=mvp2_dk;Password=tkxf4wy25DdgFz6aRHbe");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bruger>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bruger__3214EC07AC958AF1");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Campus).WithMany(p => p.Brugers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bruger__Campus_I__5629CD9C");

            entity.HasOne(d => d.Rolle).WithMany(p => p.Brugers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bruger__Rolle_Id__571DF1D5");

            entity.HasMany(d => d.Events).WithMany(p => p.Brugers)
                .UsingEntity<Dictionary<string, object>>(
                    "BrugerAdministrererEvent",
                    r => r.HasOne<Event>().WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__BrugerAdm__Event__60A75C0F"),
                    l => l.HasOne<Bruger>().WithMany()
                        .HasForeignKey("BrugerId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__BrugerAdm__Bruge__5FB337D6"),
                    j =>
                    {
                        j.HasKey("BrugerId", "EventId").HasName("PK__BrugerAd__7E63400C103D6AC0");
                        j.ToTable("BrugerAdministrererEvent");
                        j.IndexerProperty<int>("BrugerId").HasColumnName("Bruger_Id");
                        j.IndexerProperty<int>("EventId").HasColumnName("Event_Id");
                    });
        });

        modelBuilder.Entity<Campus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Campus__3214EC07ED0536DF");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<CampusHarLagerbeholdning>(entity =>
        {
            entity.HasKey(e => new { e.VareId, e.CampusId }).HasName("PK__CampusHa__23B94E1E80390066");

            entity.HasOne(d => d.Campus).WithMany(p => p.CampusHarLagerbeholdnings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CampusHar__Campu__6754599E");

            entity.HasOne(d => d.Vare).WithMany(p => p.CampusHarLagerbeholdnings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CampusHar__Vare___66603565");
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Event__3214EC078B593A16");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Kategori).WithMany(p => p.Events)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Event__Kategori___4E88ABD4");

            entity.HasOne(d => d.Nyheder).WithMany(p => p.Events)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Event__Nyheder_I__4F7CD00D");
        });

        modelBuilder.Entity<Kategori>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Kategori__3214EC07A451C6B0");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Nyheder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Nyheder__3214EC071787EAB6");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Rolle>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Rolle__3214EC07B4EAEFD7");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Tilmelding>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tilmeldi__3214EC07DD45BFF9");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Bruger).WithMany(p => p.Tilmeldings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Tilmeldin__Bruge__59FA5E80");

            entity.HasOne(d => d.Event).WithMany(p => p.Tilmeldings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Tilmeldin__Event__5AEE82B9");
        });

        modelBuilder.Entity<Vare>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Vare__3214EC0725DE7CAE");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.VareType).WithMany(p => p.Vares)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Vare__VareType_I__6383C8BA");
        });

        modelBuilder.Entity<VareType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__VareType__3214EC079B94DD16");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}