// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Rolle")]
public partial class Rolle
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Brugertype { get; set; }

    [InverseProperty("Rolle")]
    public virtual ICollection<Bruger> Brugers { get; set; } = new List<Bruger>();
}