// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Tilmelding")]
public partial class Tilmelding
{
    [Key]
    public int TilmeldtId { get; set; }

    public DateOnly Dato { get; set; }

    public int AntalTilmeldt { get; set; }

    [Column("Bruger_BrugerId")]
    public int BrugerBrugerId { get; set; }

    [Column("Event_EventId")]
    public int EventEventId { get; set; }

    [ForeignKey("BrugerBrugerId")]
    [InverseProperty("Tilmeldings")]
    public virtual Bruger BrugerBruger { get; set; }

    [ForeignKey("EventEventId")]
    [InverseProperty("Tilmeldings")]
    public virtual Event EventEvent { get; set; }
}