// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Tilmelding")]
public partial class Tilmelding
{
    [Key]
    public int Id { get; set; }

    public DateOnly Dato { get; set; }

    public int AntalTilmeldt { get; set; }

    public int BrugerId { get; set; }

    public int EventId { get; set; }

    [ForeignKey("BrugerId")]
    [InverseProperty("Tilmeldings")]
    public virtual Bruger Bruger { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("Tilmeldings")]
    public virtual Event Event { get; set; }
}