// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("VareType")]
public partial class VareType
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(45)]
    public string Navn { get; set; }

    [InverseProperty("VareType")]
    public virtual ICollection<Vare> Vares { get; set; } = new List<Vare>();
}