// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Event_Applikation.Models;

[Table("Vare")]
public partial class Vare
{
    [Key]
    public int VareId { get; set; }

    [Required]
    [StringLength(45)]
    public string VareNavn { get; set; }

    [Column("VareType_VareTypeId")]
    public int VareTypeVareTypeId { get; set; }

    [InverseProperty("VareVare")]
    public virtual ICollection<CampusHarLagerbeholdning> CampusHarLagerbeholdnings { get; set; } = new List<CampusHarLagerbeholdning>();

    [ForeignKey("VareTypeVareTypeId")]
    [InverseProperty("Vares")]
    public virtual VareType VareTypeVareType { get; set; }
}